### ISSUE TITLE
Barchart

### ISSUE THREAD

**Issue by DerekHunter** [DerekHunter/APDataSet#4]
We need a reusable bar chart built on top of d3.js. One in which we can load and unload data on the fly.

the chart should have two graphs in it, with the y axis splitting it down the middle. On the left side we'll have unranked, and hte right side will have ranked.

**Comment by DerekHunter** [comment]
should be able to use this
http://jtblin.github.io/angular-chart.js/

looks pretty easy, maybe modify it so that it looks the way im hoping it will.

**Comment by a982306** [comment]
If anything is going to decide a winner it's going to be those interactive graphs
